### ISSUE TITLE
systemfd/listenfd not working through cargo-cmd

### ISSUE THREAD

**Issue by callym** [danreeves/cargo-cmd#13]
I've got an `actix-web` app that uses the autoreloading setup from [here](https://actix.rs/docs/autoreload/), and am trying to use `cargo-cmd` to run a bash script that sets up stuff before the Rust program is run. Running the bash script works fine, but when running through `cargo cmd watch`, I get an error in my Rust code, `fd 3 is not a socket` from `listenfd`.

```
#!/bin/bash

# other setup stuff

systemfd --no-pid -s http::6660 -- cargo watch -x run
```

```
[package.metadata.commands]
watch = "./watch.sh"
```

**Comment by danreeves** [comment]
Hm, I have that same setup on a project myself. I just tried it putting it in a script and it worked fine. Do you think you could try narrowing it down a minimal reproduction so that I can investigate?

Thanks!

**Comment by callym** [comment]
Okay, I've narrowed it down to:

```
extern crate listenfd;
use listenfd::ListenFd;

fn main() {
  let mut listenfd = ListenFd::from_env();
  listenfd.take_tcp_listener(0).unwrap();
}
```

```
[package]
name = "cargo-cmd-bug"
version = "0.1.0"
authors = ["Callym <hi@callym.com>"]

[dependencies]
listenfd = "0.3"

[package.metadata.commands]
watch = "systemfd --no-pid -s http::8088 -- cargo run"
```

`cargo cmd watch` fails with the above error, running `systemfd --no-pid -s http::8088 -- cargo run` manually works fine.

**Comment by danreeves** [comment]
Thanks! I've managed to reproduce it now but I'm still digging into what's going on

**Comment by danreeves** [comment]
Actually, I'm not sure this is an issue in `cargo-cmd`. I'm getting this error when running directly through systemfd 😕 

```sh
cargo build

systemfd --no-pid -s http::3000 -- ./target/debug/cargo-cmd-bug
```

**Comment by danreeves** [comment]
Updating my rust seems to have fixed it. Can you give that a go and let me know if the issue persists? Meanwhile I've opened a listenfd https://github.com/mitsuhiko/rust-listenfd/issues/3 to see if they've got any ideas

**Comment by callym** [comment]
Finally got round to updating my Rust, and yep this seems to be fixed now!
